language: python
python:
  - "3.7"
sudo: required
services:
  - checkloop

env:
  global:
    - APP_ADDRESS=$WORD
    - APP_PASSWORD=$COLOR

before_install:
  - docker build -t jcsolutions/testb -f ./Dockerfile.dev .

script:
  - echo "skipping tests"
